### ISSUE TITLE
[FEATURE] Clicking on `close chat` should remove every info

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#127]
### Description

Clicking on `close chat` just takes you away from the chat component, if you click on `start` it takes you to the previous chat and that's not good

#### Tasks
- [ ] send a `close` event to socketio
- [ ] remove the user from the current room
- [ ] delete the room in general

**Comment by shdesarrollo** [comment]
I would like to work on it. Please assign me!

**Comment by mathiasayivor** [comment]
@Dun-sin is anyone already working on this issue?
If not, I'd like to work on it.
