### ISSUE TITLE
[FEATURE] Add menu for mobile view 

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#133]
### Description

On mobile view the navbar makes it look unresponsive.

**Tasks**
- [ ] Add a menu icon using React-icons
- [ ] make the navbar not visible on mobile
- [ ] make the navbar only visible when the menu icon is clicked
- [ ] add a close icon
- [ ] make the navbar not visible when the close icon is clicked

### Screenshots
![Screenshot_2022-10-15-12-07-11-978_com brave browser](https://user-images.githubusercontent.com/78784850/195983222-82cdf715-7d4b-4697-af61-7b802297ff12.jpg)

**Comment by Anuran12** [comment]
Hii @Dun-sin I would like to work on this.. please assign it to me.

**Comment by Dun-sin** [comment]
> Hii @Dun-sin I would like to work on this.. please assign it to me.

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Anuran12** [comment]
@Dun-sin Hey.. is there any way to run the website without mongodb ?

**Comment by Dun-sin** [comment]
> @Dun-sin Hey.. is there any way to run the website without mongodb ?

Well no, but you need the env filled

**Comment by Anuran12** [comment]
> > @Dun-sin Hey.. is there any way to run the website without mongodb ?
> 
> Well no, but you need the env filled

How ?

**Comment by Dun-sin** [comment]
> > > @Dun-sin Hey.. is there any way to run the website without mongodb ?
> > 
> > Well no, but you need the env filled
> 
> How ?

Do you know what an env is?

**Comment by Anuran12** [comment]
There is two evn_sample files. I need to change the address there after hosting local database. right ?

**Comment by Anuran12** [comment]
@Dun-sin  ??

**Comment by Dun-sin** [comment]
> There are two evn_sample files. I need to change the address there after hosting local database. right ?

No, just leave it as it is, you have no business with the backend so it should be fine.

**Comment by Anuran12** [comment]
> > There are two evn_sample files. I need to change the address there after hosting local database. right ?
> 
> No, just leave it as it is, you have no business with the backend so it should be fine.

so how can i host it. please told me. I don't have any backend knowledge

**Comment by Dun-sin** [comment]
> > > There are two evn_sample files. I need to change the address there after hosting local database. right ?
> > 
> > No, just leave it as it is, you have no business with the backend so it should be fine.
> 
> so how can i host it for testing? please told me. I don't have any backend knowledge 

You don't need to do anything with the backend, your work is in the frontend, just fill the env and leave it at that and focus on the frontend.

If you can't do it let me know

**Comment by Anuran12** [comment]
I don't know how to fill evn.

**Comment by Anuran12** [comment]
@Dun-sin Please tell me

**Comment by Dun-sin** [comment]
> @Dun-sin Please tell me

Create a new file called ".env" ,copy the things in the env_sample files and paste them in the file you created, do it for both folders.

**Comment by Dun-sin** [comment]
@Anuran12 figured it out?

**Comment by Anuran12** [comment]
@Dun-sin yea.. but 
![image](https://user-images.githubusercontent.com/104062485/195996475-5d811169-2f01-4484-be59-2bf59418fe64.png)

**Comment by Anuran12** [comment]
I did no install mongodb. do i have to install it ?

**Comment by Dun-sin** [comment]
> I did no install mongodb. do i have to install it like that video?

Yes, but leave this issue I'm closing it.

Thanks for wanting to contribute, you can checkout other easier issues.

**Comment by Anuran12** [comment]
> > I did no install mongodb. do i have to install it like that video?
> 
> Yes, but leave this issue I'm closing it.
> 
> Thanks for wanting to contribute, you can checkout other easier issues.

why? please let me solve this.

**Comment by Anuran12** [comment]
@Dun-sin  Hey i hosted it. 
![image](https://user-images.githubusercontent.com/104062485/195998615-6a11b6b3-5cf7-431a-8435-079d47281aae.png)

**Comment by Anuran12** [comment]
@Dun-sin Now tell me where can i found the hosted website. so that i could see my changes there ?
