### ISSUE TITLE
[BUG] moving to another page loses state of previous state

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#147]
### Description

when a user is in the search page and they click on the other pages, the previous state of the previous page is gone, which means if they were in a chat or were searching, they can't access that state anymore

**Tasks**
- [ ] Keep a general state for each tasks going on in the search page
- [ ] When a user is not searching and not in a chat, their current state should be `notSearching`, when they are searching, it should be `searching` and when they are in a chat with someone, it should be `Paired`
- [ ] When a user leaves a route and come back, display the component needed based on their current state

**Comment by Shivam164** [comment]
Hey @Dun-sin, I would like to work on this issue. Please assign this to me.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, I would like to work on this issue. Please assign this to me.

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Shivam164** [comment]
@Dun-sin, It is not yet assigned to me.

**Comment by Dun-sin** [comment]
hi @Shivam164, an update pls?

**Comment by mathiasayivor** [comment]
@Dun-sin I'm taking this...
