### ISSUE TITLE
[FEATURE] Add close and re-search button

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#185]
### Description

Enable users to close their current anonymous chat and automatically start searching for a new random buddy

## TODO

- [ ] Add a button labelled with something similar to `Close 'n find new buddy`
- [ ] Confirm close action from the user after clicking on the button
- [ ] After a positive confirmation from the user, close the current chat and automatically start searching for a new random buddy

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by mathiasayivor** [comment]
@Dun-sin I'm taking this one
