### ISSUE TITLE
[FEATURE] Add functionality for friends section

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#212]
### Description

This issue is dependent on when issue #210 is done

**Tasks:**
- [ ] move the chat from the anonymous chat to the friends section (close the chat in anon section but don't delete the chat and room name, create another room for the friends section with that name and display the chat data)
- [ ] move the user back to the home search page
- [ ] get the name of the friend user to display

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by mathiasayivor** [comment]
@Dun-sin  can I be assigned this?

**Comment by haszankauna** [comment]
hello @Dun-sin  can I please be assigned this?
