### ISSUE TITLE
[FEATURE] Bulk Delete

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#222]
### Description

Users should be able to delete multiple messages at once.

## TODO:
 - [ ] Enable users to select multiple messages using a checkbox
 - [ ] When multiple messages are selected, show a Cancel and a Delete button
 - [ ] When the Delete button is clicked, delete all selected messages
 - [ ] When the Cancel button is clicked, deselect all selected messages

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)
